sudo: false
language: python
matrix:
    include:
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
          env: TOXENV=flake8
          env: TOXENV=pylint
          env: TOXENV=coverage
install:
    - pip install tox
script: tox
